Fix compile fail when nolib size by add more dummy libgcc function required by m0 ./build_m0.sh
mont64.c:(.text.mulul64+0x12): undefined reference to `__aeabi_lmul'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: mont64.c:(.text.mulul64+0x22): undefined reference to `__aeabi_lmul'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: mont64.c:(.text.mulul64+0x38): undefined reference to `__aeabi_lmul'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: mont64.c:(.text.mulul64+0x5c): undefined reference to `__aeabi_lmul'
mont64.c:(.text.montmul+0x24): undefined reference to `__aeabi_lmul'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: mont64.o:mont64.c:(.text.benchmark_body+0x148): more undefined references to `__aeabi_lmul' follow
matmult-int.c:(.text.RandomInteger+0xe): undefined reference to `__aeabi_idivmod'
nettle-aes.c:(.text._aes_set_key+0x5c): undefined reference to `__aeabi_uidivmod'
libpicojpeg.c:(.text.pjpeg_decode_mcu+0x1a0): undefined reference to `__gnu_thumb1_case_uhi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0x24c): undefined reference to `__gnu_thumb1_case_uqi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0x2ec): undefined reference to `__gnu_thumb1_case_sqi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0x3ca): undefined reference to `__gnu_thumb1_case_shi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0x796): undefined reference to `__gnu_thumb1_case_uhi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0xa2a): undefined reference to `__gnu_thumb1_case_sqi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0xa6a): undefined reference to `__gnu_thumb1_case_sqi'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libpicojpeg.c:(.text.pjpeg_decode_mcu+0xaaa): undefined reference to `__gnu_thumb1_case_shi'
qrencode.c:(.text.applymask+0xc): undefined reference to `__gnu_thumb1_case_uhi'
combined.c:(.text.sglib_hashed_ilist_add+0xa): undefined reference to `__aeabi_uidivmod'
combined.c:(.text.sglib_hashed_ilist_find_member+0xa): undefined reference to `__aeabi_uidivmod'
combined.c:(.text.benchmark_body+0x10a): undefined reference to `__aeabi_idivmod'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: combined.c:(.text.benchmark_body+0x29a): undefined reference to `__aeabi_idivmod'
libst.c:(.text.RandomInteger+0xe): undefined reference to `__aeabi_idivmod'
tarfind.c:(.text.benchmark_body+0x54): undefined reference to `__aeabi_idivmod'
libud.c:(.text.ludcmp+0x3c): undefined reference to `__aeabi_idiv'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libud.c:(.text.ludcmp+0xb4): undefined reference to `__aeabi_idiv'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libud.c:(.text.ludcmp+0x140): undefined reference to `__aeabi_idiv'
libwikisort.c:(.text.WikiSort+0x3e): undefined reference to `__aeabi_idivmod'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libwikisort.c:(.text.WikiSort+0x90): undefined reference to `__aeabi_idiv'
/home/share/devtools/armgcc/arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: libwikisort.c:(.text.WikiSort+0x5d8): undefined reference to `__aeabi_idivmod'

Signed-off-by: Huaqi Fang <578567190@qq.com>